// import.....................................................
const typeDefs = require("./typeDefs");
const resolvers = require("./resolvers");

// export.....................................................
module.exports = { typeDefs, resolvers };
