const cityList = [
  {
    city: "Hong Kong",
    country: "China",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Bangkok",
    country: "Thailand",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "London",
    country: "United Kingdom",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Macau",
    country: "China",
    continent: "Asia",
    climate: "tropical;",
    image: "",
    youtube: "",
  },
  {
    city: "Singapore",
    country: "Singapore",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Paris",
    country: "France",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Dubai",
    country: "UAE",
    continent: "Asia",
    climate: "Desert",
    image: "",
    youtube: "",
  },

  {
    city: "New York City",
    country: "US",
    continent: "North America",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Kuala Lumpur",
    country: "Malaysia",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Istanbul",
    country: "Turkey",
    continent: "Asia",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },
  {
    city: "Delhi",
    country: "India",
    continent: "",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Antalya",
    country: "Turkey",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Shenzhen",
    country: "China",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Mumbai",
    country: "India",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Phuket",
    country: "Thailand",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Rome",
    country: "Italy",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Tokyo",
    country: "Japan",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Pattaya",
    country: "Thailand",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Taipei",
    country: "Taiwan",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Mecca",
    country: "Saudi Arabia",
    continent: "Asia",
    climate: "Desert",
    image: "",
    youtube: "",
  },
  {
    city: "Guangzhou",
    country: "China",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Prague",
    country: "Czechia",
    continent: "Erope",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Medina",
    country: "Saudi Arabia",
    continent: "Asia",
    climate: "Desert",
    image: "",
    youtube: "",
  },
  {
    city: "Seoul",
    country: "South Korea",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Amsterdam",
    country: "Netherlands",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Agra",
    country: "India",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Miami",
    country: "US",
    continent: "North America",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Osaka",
    country: "Japan",
    continent: "Asia",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Los Angeles",
    country: "US",
    continent: "North America",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Shanghai",
    country: "China",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Ho Chi Minh City",
    country: "Vietnam",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Denpasar",
    country: "Indonesia",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Barcelona",
    country: "Spain",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },
  {
    city: "Las Vegas",
    country: "US",
    continent: "North America",
    climate: "Desert",
    image: "",
    youtube: "",
  },

  {
    city: "Milan",
    country: "Italy",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Chennai",
    country: "India",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Vienna",
    country: "Austria",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Johor Bahru",
    country: "Malaysia",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Jaipur",
    country: "India",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Cancun",
    country: "Mexico",
    continent: "North America",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Berlin",
    country: "Germany",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Cairo",
    country: "Egypt",
    continent: "Africa",
    climate: "Desert",
    image: "",
    youtube: "",
  },

  {
    city: "Athens",
    country: "Greece",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Orlando",
    country: "US",
    continent: "North America",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Moscow",
    country: "Russia",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Venice",
    country: "Italy",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Madrid",
    country: "Spain",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Ha Long",
    country: "Vietnam",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Riyadh",
    country: "Saudi Arabia",
    continent: "Asia",
    climate: "Desert",
    image: "",
    youtube: "",
  },
  {
    city: "Dublin",
    country: "Ireland",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Florence",
    country: "Italy",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Ha Noi",
    country: "Vietnam",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Toronto",
    country: "Canada",
    continent: "North America",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Johannesburg",
    country: "South Africa",
    continent: "Africa",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Sydney",
    country: "Australia",
    continent: "Oceania",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Munich",
    country: "Germany",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Jakarta",
    country: "Indonesia",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Beijing",
    country: "China",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "St. Petersburg",
    country: "Russia",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Brussels",
    country: "Belgium",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Jerusalem",
    country: "Israel",
    continent: "Asia",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Budapest",
    country: "Hungary",
    continent: "Europe",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Lisbon",
    country: "Portugal",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Dammam",
    country: "Saudi Arabia",
    continent: "Asia",
    climate: "Desert",
    image: "",
    youtube: "",
  },

  {
    city: "Penang Island",
    country: "Malaysia",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Heraklion",
    country: "Greece",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Kyoto",
    country: "Japan",
    continent: "Asia",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Zhuhai",
    country: "China",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Vancouver",
    country: "Canada",
    continent: "North America",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Chiang Mai",
    country: "Thailand",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Copenhagen",
    country: "Denmark",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "San Francisco",
    country: "US",
    continent: "North America",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Melbourne",
    country: "Australia",
    continent: "Oceania",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Krakow",
    country: "Poland",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Marrakech",
    country: "Morocco",
    continent: "Africa",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Kolkatta",
    country: "India",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Cebu",
    country: "Philippines",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Auckland",
    country: "New Zealand",
    continent: "Oceania",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Tel Aviv",
    country: "Israel",
    continent: "Asia",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },
  {
    city: "Guilin",
    country: "China",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Honolulu",
    country: "US",
    continent: "North America",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Hurgada",
    country: "Egypt",
    continent: "Africa",
    climate: "Desert",
    image: "",
    youtube: "",
  },

  {
    city: "Warsaw",
    country: "Poland",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Mugla",
    country: "Turkey",
    continent: "Asia",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Buenos Aires City",
    country: "Argentina",
    continent: "South America",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Chiba",
    country: "Japan",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Frankfurt",
    country: "Germany",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Stockholm",
    country: "Sweden",
    continent: "Europe",
    climate: "Temperate",
    image: "",
    youtube: "",
  },
  {
    city: "Lima",
    country: "Peru",
    continent: "South America",
    climate: "Temperate",
    image: "",
    youtube: "",
  },

  {
    city: "Da Nang",
    country: "Vietnam",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Batam",
    country: "Indonesia",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Nice",
    country: "France",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Fukuoka",
    country: "Japan",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Abu Dhabi",
    country: "UAE",
    continent: "Asia",
    climate: "Desert",
    image: "",
    youtube: "",
  },

  {
    city: "Jeju",
    country: "South Korea",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Porto",
    country: "Portugal",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Rhodes",
    country: "Greece",
    continent: "Europe",
    climate: "Mediterranean",
    image: "",
    youtube: "",
  },

  {
    city: "Rio de Janeiro",
    country: "Brazil",
    continent: "South America",
    climate: "Tropical",
    image: "",
    youtube: "",
  },
  {
    city: "Krabi",
    country: "Thailand",
    continent: "Asia",
    climate: "Tropical",
    image: "",
    youtube: "",
  },

  {
    city: "Bangalore",
    country: "India",
    continent: "Asia",
    climate: "Tropical",
    image: "https://images.pexels.com/photos/2889701/pexels-photo-2889701.jpeg",
    youtube: "",
  },

  {
    city: "Reykjavik",
    Country: "Iceland",
    continent: "Europe",
    climate: "Polar",
    image: "",
    youtube: "",
  },

  {
    city: "Nepal",
    Country: "Federal Democratic Republic of Nepal",
    continent: "Asia",
    climate: "Polar",
    image: "",
    youtube: "",
  },
];
export default cityList;
