// import.....................................................
const User = require("./User");
const Reviews = require("./Reviews");

// export.....................................................
module.exports = { User, Reviews };
